# My .msg files are basically RFC2822 MIME-format documents with the eventual
# goal of each possibly containing a hierarchy of multiple sub-documents. How
# might I identify for GNU Make all the targets generated by such documents?
#
# For now, assume 1 .msg file -> pandoc -> 1 .html file.  Merely strip the
# header and use for metadata. (Convert my rfc2822 format to pandoc "title
# block" format
targets := $(targets:.msg=.md)
$(DST)/%.md: $(DST)/%.msg
	bin/rfc2822topandoc < $< > $@
